INSERT INTO students (id, name) VALUES(1, 'Matt Hooper');
INSERT INTO students (id, name) VALUES(2, 'Matt Henry');
INSERT INTO students (id, name) VALUES(3, 'Matt John');
INSERT INTO students (id, name) VALUES(4, 'Matt Kooper');
INSERT INTO students (id, name) VALUES(5, 'Deepak Vijayan');
INSERT INTO students (id, name) VALUES(6, 'Deepak V');
INSERT INTO students (id, name) VALUES(7, 'Deepak');
INSERT INTO students (id, name) VALUES(8, 'Apple');
INSERT INTO students (id, name) VALUES(9, 'Orange');
INSERT INTO students (id, name) VALUES(10, 'Apricot');
